name: upload
description: "Upload test results"
inputs:
  name-suffix:
    default: ${{ github.job }}
  test-report-retention-days:
    default: 5

runs:
  using: composite
  steps:
    - name: Upload test results
      uses: actions/upload-artifact@v3
      # Upload all test reports only on failure, because the artifacts are large
      if: failure()
      with:
        name: result ${{ inputs.name-suffix }}
        path: |
          **/target/surefire-reports
          **/target/checkstyle-*
    - name: Upload test report
      uses: actions/upload-artifact@v3
      # Always upload the test report for the annotate.yml workflow,
      # but only the single XML file to keep the artifact small
      if: always()
      with:
        # Name prefix is checked in the `Annotate checks` workflow
        name: test report ${{ inputs.name-suffix }}
        path: |
          **/surefire-reports/TEST-*.xml
        retention-days: ${{ inputs.test-report-retention-days }}
