name: cleanup

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  cancel:
    runs-on: ubuntu-latest
    steps:
      - uses: n1hility/cancel-previous-runs@v2
        with:
          token: ${{ github.token }}
          workflow: ci.yml
